version: '3'

services:
  php:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    volumes:
      - ./:/usr/src/app
    restart: on-failure
    networks:
      - poll-network

  nginx:
    image: nginx:stable-alpine
    restart: on-failure
    volumes:
      - ./:/usr/src/app
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - php
    networks:
      - poll-network

  database:
    image: mariadb:latest
    restart: on-failure
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: ${DB_NAME:-poll}
      MYSQL_USER: ${DB_USER:-poll}
      MYSQL_PASSWORD: ${DB_PASSWORD:-poll}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - poll-network

volumes:
  db-data:

networks:
  poll-network:
    driver: bridge
